import type { ResumeData } from "./index";

export const sampleResume: ResumeData = {
  basics: {
    name: "Alex Morgan",
    headline: "Software Engineer & Web Application Developer",
    email: "alex.morgan@example.com",
    phone: "+1 555 234 9876",
    location: "Remote / Global",
    url: {
      label: "",
      href: "https://example.dev",
    },
    customFields: [],
    picture: {
      url: "https://i.imgur.com/9QOQZpK.jpg",
      size: 120,
      aspectRatio: 1,
      borderRadius: 0,
      effects: {
        hidden: false,
        border: false,
        grayscale: false,
      },
    },
  },
  sections: {
    summary: {
      id: "summary",
      name: "Summary",
      columns: 1,
      separateLinks: true,
      visible: true,
      content: "<p>Versatile <strong>Software Engineer</strong> with experience in building scalable web applications and user-focused digital solutions. Skilled in both front-end and back-end development, with a strong focus on clean architecture, performance, and maintainability. Comfortable working in fast-paced and remote environments.</p>",
    },
    experience: {  // ✅ CORRECT - was "work"
      id: "experience",
      name: "Experience",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "lhw25d7gf32wgdfpsktf6e0x",
          visible: true,
          company: "Digital Solutions Co.",
          position: "Software Engineer",
          location: "Remote",
          date: "2022 to Present",
          summary: "<ul><li><p>Developed and maintained modern web applications using JavaScript and backend technologies.</p></li><li><p>Implemented RESTful APIs and integrated third-party services.</p></li><li><p>Improved application performance and code reliability through refactoring.</p></li></ul>",
          url: { label: "", href: "" },
        },
        {
          id: "r6543lil53ntrxmvel53gbtm",
          visible: true,
          company: "Creative Web Studio",
          position: "Junior Web Developer",
          location: "Hybrid",
          date: "2020 to 2022",
          summary: "<ul><li><p>Built responsive websites and interfaces using HTML, CSS, and JavaScript.</p></li><li><p>Worked closely with designers to translate mockups into functional UI.</p></li><li><p>Assisted in backend development and bug fixing.</p></li></ul>",
          url: { label: "", href: "" },
        },
      ],
    },
    education: {
      id: "education",
      name: "Education",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "yo3p200zo45c6cdqc6a2vtt3",
          visible: true,
          institution: "State University of Technology",
          studyType: "Bachelor of Science",
          area: "Computer Science",
          score: "",
          date: "2017 to 2021",
          summary: "",
          url: { label: "", href: "" },
        },
      ],
    },
    skills: {
      id: "skills",
      name: "Skills",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "hn0keriukh6c0ojktl9gsgjm",
          visible: true,
          name: "Programming",
          description: "Advanced",
          level: 0,
          keywords: ["JavaScript", "PHP", "Python"],
        },
        {
          id: "r8c3y47vykausqrgmzwg5pur",
          visible: true,
          name: "Frameworks",
          description: "Intermediate",
          level: 0,
          keywords: ["React.js", "Node.js", "Express"],
        },
        {
          id: "b5l75aseexqv17quvqgh73fe",
          visible: true,
          name: "Tools",
          description: "Intermediate",
          level: 0,
          keywords: ["Git", "Docker", "Linux", "VS Code"],
        },
      ],
    },
    projects: {
      id: "projects",
      name: "Projects",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "yw843emozcth8s1ubi1ubvlf",
          visible: true,
          name: "Task Management Web App",
          description: "Full-Stack Project",
          date: "",
          summary: "<p>Developed a task management application with authentication, CRUD features, and responsive design.</p>",
          keywords: [],
          url: { label: "", href: "" },
        },
        {
          id: "ncxgdjjky54gh59iz2t1xi1v",
          visible: true,
          name: "Portfolio Website",
          description: "Personal Project",
          date: "",
          summary: "<p>Designed and built a personal portfolio website to showcase projects and technical skills.</p>",
          keywords: [],
          url: { label: "", href: "" },
        },
      ],
    },
    profiles: {
      id: "profiles",
      name: "Profiles",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "cnbk5f0aeqvhx69ebk7hktwd",
          visible: true,
          network: "LinkedIn",
          username: "alex-morgan",
          icon: "linkedin",
          url: { label: "", href: "https://linkedin.com/in/example" },
        },
        {
          id: "ukl0uecvzkgm27mlye0wazlb",
          visible: true,
          network: "GitHub",
          username: "example-dev",
          icon: "github",
          url: { label: "", href: "https://github.com/example" },
        },
      ],
    },
    certifications: {
      id: "certifications",
      name: "Certifications",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [
        {
          id: "spdhh9rrqi1gvj0yqnbqunlo",
          visible: true,
          name: "Full-Stack Web Development",
          issuer: "Online Learning Platform",
          date: "2022",
          summary: "",
          url: { label: "", href: "" },
        },
        {
          id: "n838rddyqv47zexn6cxauwqp",
          visible: true,
          name: "Cloud Fundamentals",
          issuer: "Cloud Skills Academy",
          date: "2021",
          summary: "",
          url: { label: "", href: "" },
        },
      ],
    },
    awards: {
      id: "awards",
      name: "Awards",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [],
    },
    volunteer: {
      id: "volunteer",
      name: "Volunteering",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [],
    },
    interests: {
      id: "interests",
      name: "Interests",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [],
    },
    languages: {
      id: "languages",
      name: "Languages",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [],
    },
    publications: {
      id: "publications",
      name: "Publications",
      columns: 1,
      separateLinks: true,
      visible: true,
      items: [],
    },
    references: {
      id: "references",
      name: "References",
      columns: 1,
      separateLinks: true,
      visible: false,
      items: [
        {
          id: "f2sv5z0cce6ztjl87yuk8fak",
          visible: true,
          name: "Available upon request",
          description: "",
          summary: "",
          url: { label: "", href: "" },
        },
      ],
    },
    custom: {},
  },
  metadata: {
    template: "meridian",  // ✅ Changed from "meridian" to "apex"
    layout: [
      [
        ["summary", "experience", "education", "projects", "references"],
        ["profiles", "skills", "certifications", "interests", "languages", "awards", "volunteer", "publications"],
      ],
    ],
    css: {
      value: "",
      visible: false,
    },
    page: {
      margin: 14,
      format: "a4",
      options: {
        breakLine: true,
        pageNumbers: true,
      },
    },
    theme: {
      background: "#ffffff",
      text: "#000000",
      primary: "#ca8a04",
    },
    typography: {
      font: {
        family: "Merriweather",
        subset: "latin",
        variants: ["regular"],
        size: 13,
      },
      lineHeight: 1.75,
      hideIcons: false,
      underlineLinks: true,
    },
    notes: "",
  },
};