# # In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# # The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# # If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

# services:
#   # Database (Postgres)
#   postgres:
#     image: postgres:16-alpine
#     restart: unless-stopped
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   # Storage (for image uploads)
#   minio:
#     image: minio/minio:latest
#     restart: unless-stopped
#     command: server /data
#     ports:
#       - "9000:9000"
#     volumes:
#       - minio_data:/data
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin

#   # Chrome Browser (for printing and previews)
#   chrome:
#     image: ghcr.io/browserless/chromium:latest
#     ports: ["3001:3000"]

#     restart: unless-stopped
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     environment:
#       HEALTH: "true"
#       TOKEN: chrome_token
#       PROXY_HOST: "chrome"
#       PROXY_PORT: 3000
#       PROXY_SSL: "false"

#   # Application
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: reactive-resume-local

#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#       - minio
#       - chrome
#     environment:
#       # -- Environment Variables --
#       PORT: 3000
#       NODE_ENV: production

#       # -- URLs --
#       PUBLIC_URL: http://localhost:3000
#       STORAGE_URL: http://localhost:9000/default

#       # -- Printer (Chrome) --
#       CHROME_TOKEN: chrome_token
#       CHROME_URL: ws://chrome:3000

#       # -- Database (Postgres) --
#       DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

#       # -- Auth --
#       ACCESS_TOKEN_SECRET: access_token_secret
#       REFRESH_TOKEN_SECRET: refresh_token_secret

#       # -- Emails --
#       MAIL_FROM: noreply@localhost
#       # SMTP_URL: smtp://user:pass@smtp:587

#       # -- Storage (Minio) --
#       STORAGE_ENDPOINT: minio
#       STORAGE_PORT: 9000
#       STORAGE_REGION: us-east-1
#       STORAGE_BUCKET: default
#       STORAGE_ACCESS_KEY: minioadmin
#       STORAGE_SECRET_KEY: minioadmin
#       STORAGE_USE_SSL: "false"
#       STORAGE_SKIP_BUCKET_CHECK: "false"

# volumes:
#   minio_data:
#   postgres_data:




# In this Docker Compose example, it assumes that you maintain a reverse proxy externally (or chose not to).
# The only two exposed ports here are from minio (:9000) and the app itself (:3000).
# If these ports are changed, ensure that the env vars passed to the app are also changed accordingly.

version: '3.8'  # Added version

services:
  # Database (Postgres)
  postgres:
    image: postgres:16-alpine
    container_name: rr-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reactive_resume
      POSTGRES_USER: rr_user
      POSTGRES_PASSWORD: rr_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"  # Expose for local development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rr_user -d reactive_resume"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  # Redis Cache (for Assistant, Session, Rate Limiting)
  redis:
    image: redis:7-alpine
    container_name: rr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Expose for local development
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Optional config file
    command: >
      redis-server
      --appendonly yes
      --requirepass redis_password_123
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Insight (Optional - GUI for Redis)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: rr-redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis

  # Storage (for image uploads)
  minio:
    image: minio/minio:latest
    container_name: rr-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Chrome Browser (for printing and previews)
  chrome:
    image: ghcr.io/browserless/chromium:latest
    container_name: rr-chrome
    ports: 
      - "3001:3000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HEALTH: "true"
      TOKEN: chrome_token
      PROXY_HOST: "chrome"
      PROXY_PORT: 3000
      PROXY_SSL: "false"
      # Resource limits for stability
      CONNECTION_TIMEOUT: 30000
      MAX_CONCURRENT_SESSIONS: 10
      QUEUE_LENGTH: 10
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: reactive-resume-local
    container_name: rr-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      chrome:
        condition: service_started
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=1024"

      # -- URLs --
      PUBLIC_URL: http://localhost:3000
      STORAGE_URL: http://localhost:9000/default
      API_URL: http://localhost:3000/api
      ASSISTANT_URL: http://localhost:3000/api/assistant

      # -- Printer (Chrome) --
      CHROME_TOKEN: chrome_token
      CHROME_URL: ws://chrome:3000

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://rr_user:rr_password_123@postgres:5432/reactive_resume

      # -- Redis Cache --
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password_123
      REDIS_DB: 0
      REDIS_TLS: "false"

      # -- Assistant Configuration --
      GROQ_API_KEY: ${GROQ_API_KEY:-}  # Will be set from .env file
      ASSISTANT_ENABLED: "true"
      ASSISTANT_RATE_LIMIT_ENABLED: "true"
      ASSISTANT_CACHE_ENABLED: "true"
      
      # -- Assistant Rate Limits --
      FREE_TIER_DAILY_LIMIT: "20"
      PREMIUM_TIER_DAILY_LIMIT: "1000"
      FREE_TIER_MINUTE_LIMIT: "5"
      PREMIUM_TIER_MINUTE_LIMIT: "100"
      
      # -- Cache TTLs (seconds) --
      USER_CONTEXT_TTL: "3600"
      CONVERSATION_TTL: "1800"
      MEMORY_SEARCH_TTL: "900"
      TIER_CACHE_TTL: "300"

      # -- Auth --
      ACCESS_TOKEN_SECRET: access_token_secret_change_in_production
      REFRESH_TOKEN_SECRET: refresh_token_secret_change_in_production
      JWT_EXPIRATION: "7d"

      # -- Emails --
      MAIL_FROM: noreply@localhost
      # SMTP_URL: smtp://user:pass@smtp:587

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: "false"
      STORAGE_SKIP_BUCKET_CHECK: "false"

      # -- Monitoring & Logging --
      LOG_LEVEL: "info"
      ENABLE_METRICS: "true"
      ENABLE_HEALTH_CHECKS: "true"

    volumes:
      # Mount for hot reload in development (optional)
      - ./backend:/app/backend:cached
      - ./frontend:/app/frontend:cached
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
      
      # Mount .env file
      - ./.env:/app/.env:ro

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"

    # Command
    command: >
      sh -c "
      echo 'Waiting for dependencies...' &&
      sleep 10 &&
      echo 'Starting application...' &&
      npm start
      "

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    container_name: rr-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  # Optional: Traefik for reverse proxy (if needed)
  # traefik:
  #   image: traefik:v3.0
  #   container_name: rr-traefik
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8081:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  minio_data:
  postgres_data:
  redis_data:
  redis_insight_data:

networks:
  default:
    name: rr-network
    driver: bridge
